### ISSUE TITLE
Caching images?

### ISSUE THREAD

**Issue by aske-cph** [leewillis77/cached-embed#4]
Hi and thanks for a great plugin!

After adding to my site a have a -maybe broadly scoped- question about the nature of embeds.

What is the benefit of caching only the string data when a page with - say 10 embeds-  still has to make upwards of 100 external requests to images, icons etc (_for example with instagram, twitter, facebook, yt_)

I guess caching everything locally or  taking a "preview" image with selenium isn't allowed - is this the same in Wordpress for example?

As far as i can se you don't really notice any change in speed as the external servers are still requested, just not the initial oembed object which is a minuscule amount of network load, so i don't really get the benefit without also caching design-elements like images, icons etc?

Right now i am trying to build a solution where a page with a lot of embeds loads in a flash, but that ends up in scenarios where you take an image of the embed on first load, then serve that, and only update the image after loads, which seems overly complex.

Thanks in advance :)

**Comment by leewillis77** [comment]
Embedded content generally needs to be inserted into the document that you serve back to the browser. If you calculate the embed every time, then you potentially have to handle that network request and parsing every time you serve that page which makes *your* page performance dependent on a 3rd party service.

If the page contains multiple embeds then that's also likely to be a serialised string of tasks that aren't carried out in parallel, but instead one after the other - all of which block the page being returned to the client browser. 

Once the browser has a page it's likely that it will launch of its requests for other resources in parallel. Many of those can be satisfied via various caches along the way anyway as they're common assets so will be in browser caches / edge caches etc.

This will reduce server load, reduce bandwidth usage, and reduce time to render pages.

As you noted though, that's only part of the puzzle.

Hope that helps.

**Comment by aske-cph** [comment]
Thanks for the great answer!
 
I see how this is actually much more efficient ie. not served as external services in an iframe which as i now realize also bootstraps the entire framwork en each request.

Back to the drawing boards..
